# Generated by Django 5.0.6 on 2024-06-24 18:18

from django.db import migrations


def create_unique_brands_name(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoes')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()

    unique_brands.objects.bulk_create([unique_brands(brand=shoe_brand) for shoe_brand in unique_brands_names])


def reverse_create_unique_brands_name(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrand')
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [migrations.RunPython(
        create_unique_brands_name,
        reverse_create_unique_brands_name)
    ]
