# Generated by Django 5.0.6 on 2024-06-25 18:07

from django.db import migrations


def set_item_rarity(apps, schema_editor):
    item_module = apps.get_model('main_app', 'Item')
    items_price = item_module.objects.all()

    for item in items_price:
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"

    item_module.objects.bulk_update(items_price, ['rarity'])


def set_item_rarity_default(apps, schema_editor):
    item_module = apps.get_model('main_app', 'Item')

    for item in item_module.objects.all():
        item.rarity = item_module._meta.get_field("rarity").default

    item_module.objects.bulk_update(item_module, ['rarity'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_item_rarity, set_item_rarity_default)
    ]
